// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReservation.proto

package carreservation;

public interface LoginCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.LoginCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
