// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReservation.proto

package carreservation;

public interface UnlockCarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.UnlockCarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool unloocked = 1;</code>
   */
  boolean getUnloocked();
}
