// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReservation.proto

package carreservation;

public interface UnlockCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.UnlockCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
