// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarsOptions.proto

package CarsOptions;

public interface CarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carsOptions.CarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model = 1;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 1;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>int32 price = 2;</code>
   */
  int getPrice();
}
