// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarsOptions.proto

package CarsOptions;

public interface CarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carsOptions.CarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string car = 1;</code>
   */
  java.lang.String getCar();
  /**
   * <code>string car = 1;</code>
   */
  com.google.protobuf.ByteString
      getCarBytes();
}
