// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarsOptions.proto

package CarsOptions;

public final class CarsOptionsServiceImpl {
  private CarsOptionsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carsOptions_CarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carsOptions_CarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carsOptions_CarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carsOptions_CarResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CarsOptions.proto\022\013carsOptions\"\031\n\nCarR" +
      "equest\022\013\n\003car\030\001 \001(\t\"+\n\013CarResponse\022\r\n\005mo" +
      "del\030\001 \001(\t\022\r\n\005price\030\002 \001(\0052R\n\013CarsOptions\022" +
      "C\n\nRequestCar\022\027.carsOptions.CarRequest\032\030" +
      ".carsOptions.CarResponse\"\0000\001B\'\n\013CarsOpti" +
      "onsB\026CarsOptionsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_carsOptions_CarRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_carsOptions_CarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carsOptions_CarRequest_descriptor,
        new java.lang.String[] { "Car", });
    internal_static_carsOptions_CarResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_carsOptions_CarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carsOptions_CarResponse_descriptor,
        new java.lang.String[] { "Model", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
