// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarSelection.proto

package carselection;

public interface ChooseCarResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarSelection.ChooseCarResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length1 = 1;</code>
   */
  int getLength1();
}
