// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarSelection.proto

package carselection;

public interface ChooseCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarSelection.ChooseCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val3 = 1;</code>
   */
  java.lang.String getVal3();
  /**
   * <code>string val3 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal3Bytes();
}
