// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarSelection.proto

package carselection;

public interface SelectCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarSelection.SelectCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val1 = 1;</code>
   */
  java.lang.String getVal1();
  /**
   * <code>string val1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getVal1Bytes();
}
