// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReturn.proto

package carreturn;

public interface CarFeedbackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.CarFeedbackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
