// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReturn.proto

package carreturn;

public final class CarReturnServiceImpl {
  private CarReturnServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_CarReturnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_CarReturnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_CarReturnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_CarReturnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_CarFeedbackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_CarFeedbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_CarFeedbackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_CarFeedbackResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CarReturn.proto\022\007strings\"#\n\021CarReturnR" +
      "esponse\022\016\n\006length\030\001 \001(\005\"\037\n\020CarReturnRequ" +
      "est\022\013\n\003val\030\001 \001(\t\"!\n\022CarFeedbackRequest\022\013" +
      "\n\003val\030\001 \001(\t\"\"\n\023CarFeedbackResponse\022\013\n\003va" +
      "l\030\001 \001(\t2\235\001\n\tCarReturn\022D\n\tCarReturn\022\031.str" +
      "ings.CarReturnRequest\032\032.strings.CarRetur" +
      "nResponse(\001\022J\n\013CarFeedback\022\033.strings.Car" +
      "FeedbackRequest\032\034.strings.CarFeedbackRes" +
      "ponse0\001B#\n\tcarreturnB\024CarReturnServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_strings_CarReturnResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strings_CarReturnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_CarReturnResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_strings_CarReturnRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strings_CarReturnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_CarReturnRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_strings_CarFeedbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_strings_CarFeedbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_CarFeedbackRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_strings_CarFeedbackResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_strings_CarFeedbackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_CarFeedbackResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
