// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReturn.proto

package carReturn;

public interface CarReturnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarReturnService.CarReturnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string returnOk = 1;</code>
   */
  java.lang.String getReturnOk();
  /**
   * <code>string returnOk = 1;</code>
   */
  com.google.protobuf.ByteString
      getReturnOkBytes();
}
