// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReturn.proto

package carreturn;

public interface CarReturnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.CarReturnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
