// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarReturn.proto

package carReturn;

public interface CarReturnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarReturnService.CarReturnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();
}
